language: scala
# Don't really need sudo, just need more memory!
sudo: required
# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.sbt/launchers
    - $HOME/build
    - $HOME/myenv
jdk:
  - oraclejdk8
scala:
  - 2.11.8
before_install:
  - pip install --user virtualenv
  - virtualenv myenv
  - source myenv/bin/activate
  - export PATH=myenv/bin/:$PATH
  - pip install --upgrade pip
  - pip install spacy
  - pip install nose codecov coverage pep8 pylint sphinx
  - pip install -r requirements.txt
  - python -m spacy download en
script:
  - ./build/sbt scalastyle
  - ./build/sbt clean coverage compile package pack test coverageReport
  - bash <(curl -s https://codecov.io/bash) -cF scala || echo "No Scala report uploaded"
  - "pep8 --ignore=E402 sparklingml/"
  - "find ./target |grep -i jar"
  - "nosetests --logging-level=INFO --detailed-errors --verbosity=2 --with-coverage --cover-html-dir=./htmlcov --cover-package=sparklingml --with-doctest --doctest-options=+ELLIPSIS"
  - coverage --combine
  - bash <(curl -s https://codecov.io/bash) -cF python || echo "No Python report uploaded"
sudo: false