language: scala

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.sbt/launchers
    - $HOME/build
    - $HOME/myenv
jdk:
  - oraclejdk8
scala:
  - 2.11.8
after_success:
  - bash <(curl -s https://codecov.io/bash) -cF scala
before_install:
  - pip install --user virtualenv
  - virtualenv myenv
  - source myenv/bin/activate
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install pep8 pylint sphinx
script:
  - ./build/sbt clean coverage compile test coverageReport
  - "pep8 --ignore=E402 sparklingml/"
sudo: false